<?php

namespace Ads\AdvertsBundle\Repository\Entity;

use Doctrine\ORM\Query\Expr;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEmplois($limit =4)
    {
        // renvoie les emploie t evenement avec ou sans photo avec un etat false
        $query = $this->getEntityManager()->createQuery("SELECT a FROM \Ads\AdvertsBundle\Entity\Annonce a LEFT JOIN \Ads\AdvertsBundle\Entity\Categorie c WITH a.idcategorie = c.id WHERE a.etat = :valetat
            ORDER BY a.id DESC")
            ->setParameters(['valetat'=>false]);
//        $query = $this->getEntityManager()->createQuery("SELECT a FROM \Ads\AdvertsBundle\Entity\Annonce a LEFT JOIN \Ads\AdvertsBundle\Entity\Categorie c WITH a.idcategorie = c.id AND c.nomcate = :valnomcat OR c.nomcate = :valnomcatt
//                 ORDER BYa.id DESC")->setMaxResults(4)->setFirstResult($offset)
//            ->setParameters(['valnomcat'=>'emploi','valnomcatt'=>'evenement','valphoto'=>'null']);

        return $query->getResult();
    }

    public function getAllAds()
    {
        $query = $this->getEntityManager()->createQuery("SELECT a FROM \Ads\AdvertsBundle\Entity\Annonce a LEFT JOIN \Ads\AdvertsBundle\Entity\Categorie c WITH a.idcategorie = c.id ORDER BY a.id DESC");

        return $query->getResult();
   }

    public function getMyAds($user)
    {
        // renvoie les annonce publier par un user donné
        $query = $this->getEntityManager()->createQuery("SELECT a FROM \Ads\AdvertsBundle\Entity\Annonce a WHERE a.idclient = :validc ORDER BY a.id DESC")
            ->setParameters(['validc'=>$user]);
        return $query->getResult();
    }
}
