<?php

namespace Ads\AdvertsBundle\Repository;

/**
 * messagerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class messagerieRepository extends \Doctrine\ORM\EntityRepository
{
}
