<?php

namespace Ads\AdvertsBundle\Repository\Entity;

/**
 * SscatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SscatRepository extends \Doctrine\ORM\EntityRepository
{
}
